const iu = {
   info: {
      name: 'IU',
      verified: true,
      followers: 8920393,
      monthlyListeners: 6938273,
      profilePhoto: 'iu-profile-photo.png',
   },
   discography: [
      {
         title: "IU 5th Album 'LILAC'",
         discType: 'Album',
         coverArt: 'iu-lilac-cover.png',
         label: '2021 EDAM Entertainment',
         releaseDate: '2021-03-25',
         duration: '00:36:31',
         tracks: [
            [
               {
                  title: 'LILAC',
                  duration: '00:03:34',
                  isExplicit: false,
                  plays: 170620309,
                  sourceFile: '/path/to/LILAC.flac',
               },
               {
                  title: 'Flu',
                  duration: '00:03:08',
                  isExplicit: false,
                  plays: 15203421,
                  sourceFile: '/path/to/Flu.flac',
               },
               {
                  title: 'Coin',
                  duration: '00:03:13',
                  isExplicit: false,
                  plays: 20394823,
                  sourceFile: '/path/to/Coin.flac',
               },
               {
                  title: 'Hi spring Bye',
                  duration: '00:05:24',
                  isExplicit: false,
                  plays: 12908345,
                  sourceFile: '/path/to/HiSpringBye.flac',
               },
               {
                  title: 'Celebrity',
                  duration: '00:03:15',
                  isExplicit: false,
                  plays: 83928374,
                  sourceFile: '/path/to/Celebrity.flac',
               },
               {
                  title: 'Troll (feat. DEAN)',
                  duration: '00:03:09',
                  isExplicit: false,
                  plays: 20874365,
                  sourceFile: '/path/to/Troll.flac',
               },
               {
                  title: 'Empty Cup',
                  duration: '00:02:19',
                  isExplicit: false,
                  plays: 18347563,
                  sourceFile: '/path/to/EmptyCup.flac',
               },
               {
                  title: 'My Sea',
                  duration: '00:05:16',
                  isExplicit: false,
                  plays: 21567392,
                  sourceFile: '/path/to/MySea.flac',
               },
               {
                  title: 'Ah Puh',
                  duration: '00:03:20',
                  isExplicit: false,
                  plays: 19287463,
                  sourceFile: '/path/to/AhPuh.flac',
               },
               {
                  title: 'Epilogue',
                  duration: '00:03:49',
                  isExplicit: false,
                  plays: 17654321,
                  sourceFile: '/path/to/Epilogue.flac',
               },
            ],
         ],
      },
      {
         title: 'Love poem',
         discType: 'Album',
         coverArt: 'iu-love-poem-cover.png',
         label: '2019 Kakao Entertainment',
         releaseDate: '2019-11-18',
         duration: '00:24:58',
         tracks: [
            [
               {
                  title: 'unlucky',
                  duration: '00:03:51',
                  isExplicit: false,
                  plays: 20567890,
                  sourceFile: '/path/to/unlucky.flac',
               },
               {
                  title: 'The visitor',
                  duration: '00:03:51',
                  isExplicit: false,
                  plays: 18907654,
                  sourceFile: '/path/to/TheVisitor.flac',
               },
               {
                  title: 'Blueming',
                  duration: '00:03:37',
                  isExplicit: false,
                  plays: 89302938,
                  sourceFile: '/path/to/Blueming.flac',
               },
               {
                  title: 'above the time',
                  duration: '00:05:00',
                  isExplicit: false,
                  plays: 21345678,
                  sourceFile: '/path/to/AboveTheTime.flac',
               },
               {
                  title: 'Lullaby',
                  duration: '00:04:21',
                  isExplicit: false,
                  plays: 27654321,
                  sourceFile: '/path/to/Lullaby.flac',
               },
               {
                  title: 'Love poem',
                  duration: '00:04:18',
                  isExplicit: false,
                  plays: 30876543,
                  sourceFile: '/path/to/LovePoem.flac',
               },
            ],
         ],
      },
      {
         title: 'BBIBBI',
         discType: 'Single',
         coverArt: 'iu-bbibbi-cover.png',
         label: '2018 Kakao Entertainment',
         releaseDate: '2018-10-10',
         duration: '00:03:14',
         tracks: [
            [
               {
                  title: 'BBIBBI',
                  duration: '00:03:14',
                  isExplicit: false,
                  plays: 175567890,
                  sourceFile: '/path/to/BBIBBI.flac',
               },
            ],
         ],
      },
   ],
};

const taeyeon = {
   info: {
      name: 'Taeyeon',
      verified: true,
      followers: 2835456,
      monthlyListeners: 4513653,
      profilePhoto: 'taeyeon-profile-photo.png',
   },
   discography: [
      {
         title: 'My Voice - The 1st Album (Deluxe Edition)',
         discType: 'Album',
         coverArt: 'taeyeon-my-voice-cover.png',
         label: '2017 SM Entertainment',
         releaseDate: '2017-04-05',
         duration: '00:55:45',
         tracks: [
            [
               {
                  title: 'Make Me Love You',
                  duration: '00:03:33',
                  isExplicit: false,
                  plays: 23674598,
                  sourceFile: '/path/to/MakeMeLoveYou.flac',
               },
               {
                  title: 'Fine',
                  duration: '00:03:29',
                  isExplicit: false,
                  plays: 37654321,
                  sourceFile: '/path/to/Fine.flac',
               },
               {
                  title: 'Cover Up',
                  duration: '00:03:25',
                  isExplicit: false,
                  plays: 18907654,
                  sourceFile: '/path/to/CoverUp.flac',
               },
               {
                  title: 'Feel So Fine',
                  duration: '00:03:39',
                  isExplicit: false,
                  plays: 20567890,
                  sourceFile: '/path/to/FeelSoFine.flac',
               },
               {
                  title: 'I Got Love',
                  duration: '00:03:10',
                  isExplicit: false,
                  plays: 40876543,
                  sourceFile: '/path/to/IGotLove.flac',
               },
               {
                  title: "I'm OK",
                  duration: '00:03:34',
                  isExplicit: false,
                  plays: 23456789,
                  sourceFile: '/path/to/ImOK.flac',
               },
               {
                  title: 'Time Lapse',
                  duration: '00:04:14',
                  isExplicit: false,
                  plays: 27654321,
                  sourceFile: '/path/to/TimeLapse.flac',
               },
               {
                  title: 'Sweet Love',
                  duration: '00:03:04',
                  isExplicit: false,
                  plays: 32098765,
                  sourceFile: '/path/to/SweetLove.flac',
               },
               {
                  title: 'When I Was Young',
                  duration: '00:03:52',
                  isExplicit: false,
                  plays: 19876543,
                  sourceFile: '/path/to/WhenIWasYoung.flac',
               },
               {
                  title: 'I Blame On You',
                  duration: '00:03:23',
                  isExplicit: false,
                  plays: 2930482,
                  sourceFile: '/path/to/IBlameOnYou.flac',
               },
               {
                  title: 'Lonely Night',
                  duration: '00:03:43',
                  isExplicit: false,
                  plays: 28765432,
                  sourceFile: '/path/to/LonelyNight.flac',
               },
               {
                  title: '11:11',
                  duration: '00:03:43',
                  isExplicit: false,
                  plays: 77283940,
                  sourceFile: '/path/to/1111.flac',
               },
               {
                  title: 'Love in Color',
                  duration: '00:02:57',
                  isExplicit: false,
                  plays: 18907654,
                  sourceFile: '/path/to/LoveInColor.flac',
               },
               {
                  title: 'Fire',
                  duration: '00:03:07',
                  isExplicit: false,
                  plays: 32098765,
                  sourceFile: '/path/to/Fire.flac',
               },
               {
                  title: 'Eraser',
                  duration: '00:02:54',
                  isExplicit: false,
                  plays: 28765432,
                  sourceFile: '/path/to/Eraser.flac',
               },
               {
                  title: 'Curtain Call',
                  duration: '00:03:52',
                  isExplicit: false,
                  plays: 19876543,
                  sourceFile: '/path/to/CurtainCall.flac',
               },
            ],
         ],
      },
      {
         title: 'INVU - The 3rd Album',
         discType: 'Album',
         coverArt: 'taeyeon-invu-cover.png',
         label: '2022 SM Entertainment',
         releaseDate: '2022-02-14',
         duration: '00:42:26',
         tracks: [
            [
               {
                  title: 'INVU',
                  duration: '00:03:24',
                  isExplicit: false,
                  plays: 83728394,
                  sourceFile: '/path/to/INVU.flac',
               },
               {
                  title: 'Some Nights',
                  duration: '00:03:27',
                  isExplicit: false,
                  plays: 2938495,
                  sourceFile: '/path/to/SomeNights.flac',
               },
               {
                  title: "Can't Control Myself",
                  duration: '00:03:01',
                  isExplicit: false,
                  plays: 12829302,
                  sourceFile: '/path/to/CantControllMyself.flac',
               },
               {
                  title: 'Set Myself On Fire',
                  duration: '00:02:37',
                  isExplicit: false,
                  plays: 74839401,
                  sourceFile: '/path/to/SetMyselfOnFire.flac',
               },
               {
                  title: 'Toddler',
                  duration: '00:03:08',
                  isExplicit: false,
                  plays: 2938495,
                  sourceFile: '/path/to/Toddler.flac',
               },
               {
                  title: 'Siren',
                  duration: '00:03:09',
                  isExplicit: false,
                  plays: 19283742,
                  sourceFile: '/path/to/Siren.flac',
               },
               {
                  title: 'Cold As Hell',
                  duration: '00:02:44',
                  isExplicit: false,
                  plays: 29384930,
                  sourceFile: '/path/to/ColdAsHell.flac',
               },
               {
                  title: 'Timeless',
                  duration: '00:03:22',
                  isExplicit: false,
                  plays: 28392817,
                  sourceFile: '/path/to/Timeless.flac',
               },
               {
                  title: 'Heart',
                  duration: '00:03:52',
                  isExplicit: false,
                  plays: 3948372,
                  sourceFile: '/path/to/Heart.flac',
               },
               {
                  title: 'No Love Again',
                  duration: '00:03:14',
                  isExplicit: false,
                  plays: 59382718,
                  sourceFile: '/path/to/NoLoveAgain.flac',
               },
               {
                  title: 'You Better Not',
                  duration: '00:02:34',
                  isExplicit: false,
                  plays: 8293842,
                  sourceFile: '/path/to/YouBetterNot.flac',
               },
               {
                  title: 'Weekend',
                  duration: '00:03:53',
                  isExplicit: false,
                  plays: 89293899,
                  sourceFile: '/path/to/Weekend.flac',
               },
               {
                  title: 'Ending Credits',
                  duration: '00:03:45',
                  isExplicit: false,
                  plays: 2839483,
                  sourceFile: '/path/to/EndingCredits.flac',
               },
            ],
         ],
      },
   ],
};
